package com.something.core.enums;

import lombok.Getter;

@Getter
public enum WxRespEnum {
    SYSTEM_BUSY(-1, "系统繁忙，此时请开发者稍候再试"),
    SUCCESS(0, "请求成功"),
    INVALID_APP_SECRET(40001, "获取 access_token 时 AppSecret 错误，或者 access_token 无效。请开发者认真比对 AppSecret 的正确性，或查看是否正在为恰当的公众号调用接口"),
    ILLEGAL_CREDENTIAL_TYPE(40002, "不合法的凭证类型"),
    ILLEGAL_OPENID(40003, "不合法的 OpenID ，请开发者确认 OpenID （该用户）是否已关注公众号，或是否是其他公众号的 OpenID"),
    ILLEGAL_MEDIA_FILE_TYPE(40004, "不合法的媒体文件类型"),
    ILLEGAL_FILE_TYPE(40005, "不合法的文件类型"),
    ILLEGAL_FILE_SIZE(40006, "不合法的文件大小"),
    ILLEGAL_MEDIA_ID(40007, "不合法的媒体文件 id"),
    ILLEGAL_MESSAGE_TYPE(40008, "不合法的消息类型"),
    ILLEGAL_IMAGE_SIZE(40009, "不合法的图片文件大小"),
    ILLEGAL_VOICE_SIZE(40010, "不合法的语音文件大小"),
    ILLEGAL_VIDEO_SIZE(40011, "不合法的视频文件大小"),
    ILLEGAL_THUMBNAIL_SIZE(40012, "不合法的缩略图文件大小"),
    ILLEGAL_APPID(40013, "不合法的 AppID ，请开发者检查 AppID 的正确性，避免异常字符，注意大小写"),
    ILLEGAL_ACCESS_TOKEN(40014, "不合法的 access_token ，请开发者认真比对 access_token 的有效性（如是否过期），或查看是否正在为恰当的公众号调用接口"),
    ILLEGAL_MENU_TYPE(40015, "不合法的菜单类型"),
    ILLEGAL_BUTTON_COUNT(40016, "不合法的按钮个数"),
    ILLEGAL_BUTTON_TYPE(40017, "不合法的按钮类型"),
    ILLEGAL_BUTTON_NAME_LENGTH(40018, "不合法的按钮名字长度"),
    ILLEGAL_BUTTON_KEY_LENGTH(40019, "不合法的按钮 KEY 长度"),
    ILLEGAL_BUTTON_URL_LENGTH(40020, "不合法的按钮 URL 长度"),
    ILLEGAL_MENU_VERSION(40021, "不合法的菜单版本号"),
    ILLEGAL_SUBMENU_LEVEL(40022, "不合法的子菜单级数"),
    ILLEGAL_SUBMENU_BUTTON_COUNT(40023, "不合法的子菜单按钮个数"),
    ILLEGAL_SUBMENU_BUTTON_TYPE(40024, "不合法的子菜单按钮类型"),
    ILLEGAL_SUBMENU_BUTTON_NAME_LENGTH(40025, "不合法的子菜单按钮名字长度"),
    ILLEGAL_SUBMENU_BUTTON_KEY_LENGTH(40026, "不合法的子菜单按钮 KEY 长度"),
    ILLEGAL_SUBMENU_BUTTON_URL_LENGTH(40027, "不合法的子菜单按钮 URL 长度"),
    ILLEGAL_CUSTOM_MENU_USER(40028, "不合法的自定义菜单使用用户"),
    INVALID_OAUTH_CODE(40029, "无效的 oauth_code"),
    ILLEGAL_REFRESH_TOKEN(40030, "不合法的 refresh_token"),
    ILLEGAL_OPENID_LIST(40031, "不合法的 openid 列表"),
    ILLEGAL_OPENID_LIST_LENGTH(40032, "不合法的 openid 列表长度"),
    ILLEGAL_REQUEST_CHARACTERS(40033, "不合法的请求字符，不能包含 \\uxxxx 格式的字符"),
    ILLEGAL_PARAMETER(40035, "不合法的参数"),
    ILLEGAL_REQUEST_FORMAT(40038, "不合法的请求格式"),
    ILLEGAL_URL_LENGTH(40039, "不合法的 URL 长度"),
    INVALID_URL(40048, "无效的url"),
    ILLEGAL_GROUP_ID(40050, "不合法的分组 id"),
    ILLEGAL_GROUP_NAME(40051, "分组名字不合法"),
    ILLEGAL_ARTICLE_IDX(40060, "删除单篇图文时，指定的 article_idx 不合法"),
    ILLEGAL_GROUP_NAME_2(40117, "分组名字不合法"),
    ILLEGAL_MEDIA_ID_SIZE(40118, "media_id 大小不合法"),
    BUTTON_TYPE_ERROR(40119, "button 类型错误"),
    SUB_BUTTON_TYPE_ERROR(40120, "子 button 类型错误"),
    ILLEGAL_MEDIA_ID_TYPE(40121, "不合法的 media_id 类型"),
    INVALID_APPSECRET(40125, "无效的appsecret"),
    ILLEGAL_WECHAT_ID(40132, "微信号不合法"),
    UNSUPPORTED_IMAGE_FORMAT(40137, "不支持的图片格式"),
    NO_EXTERNAL_LINKS(40155, "请勿添加其他公众号的主页链接"),
    OAUTH_CODE_USED(40163, "oauth_code已使用"),
    EMPTY_TITLE(40227, "标题为空"),
    APPSECRET_FROZEN(40243, "AppSecret已被冻结，请登录MP解冻后再次调用"),
    UNSUPPORTED_MARKETING_MESSAGE(40249, "不支持下发营销/推广类的消息内容"),
    NONSTANDARD_MESSAGE_CONTENT(40250, "下发消息内容不规范（包含空值等），建议检查内容规范性后再下发"),
    ACCOUNT_LIMIT_REACHED(40251, "因历史违规导致平台限制账号调用上限，当前已到达下发上限"),
    CONTENT_UNDER_REVIEW(40252, "正在调用的模板下发的部分内容已进入平台审核流程，在审核完成前，相关内容暂时无法下发"),
    NO_WECHAT_STORE_JUMP(40255, "api菜单不支持跳转微信小店"),
    MISSING_ACCESS_TOKEN(41001, "缺少 access_token 参数"),
    MISSING_APPID(41002, "缺少 appid 参数"),
    MISSING_REFRESH_TOKEN(41003, "缺少 refresh_token 参数"),
    MISSING_SECRET(41004, "缺少 secret 参数"),
    MISSING_MEDIA_DATA(41005, "缺少多媒体文件数据"),
    MISSING_MEDIA_ID(41006, "缺少 media_id 参数"),
    MISSING_SUBMENU_DATA(41007, "缺少子菜单数据"),
    MISSING_OAUTH_CODE(41008, "缺少 oauth code"),
    MISSING_OPENID(41009, "缺少 openid"),
    ACCESS_TOKEN_EXPIRED(42001, "access_token 超时，请检查 access_token 的有效期，请参考基础支持 - 获取 access_token 中，对 access_token 的详细机制说明"),
    REFRESH_TOKEN_EXPIRED(42002, "refresh_token 超时"),
    OAUTH_CODE_EXPIRED(42003, "oauth_code 超时"),
    TOKEN_INVALIDATED(42007, "用户修改微信密码， accesstoken 和 refreshtoken 失效，需要重新授权"),
    RAPID_MEDIA_ID_BROADCAST(42010, "相同 media_id 群发过快，请重试"),
    REQUIRES_GET_REQUEST(43001, "需要 GET 请求"),
    REQUIRES_POST_REQUEST(43002, "需要 POST 请求"),
    REQUIRES_HTTPS_REQUEST(43003, "需要 HTTPS 请求"),
    REQUIRES_SUBSCRIBER(43004, "需要接收者关注"),
    REQUIRES_FRIEND_RELATION(43005, "需要好友关系"),
    REQUIRES_BLACKLIST_REMOVAL(43019, "需要将接收者从黑名单中移除"),
    TEMPLATE_ABUSE_RESTRICTED(43116, "该模板因滥用被滥用过多，已被限制下发"),
    EMPTY_MEDIA_FILE(44001, "多媒体文件为空"),
    EMPTY_POST_DATA(44002, "POST 的数据包为空"),
    EMPTY_NEWS_CONTENT(44003, "图文消息内容为空"),
    EMPTY_TEXT_CONTENT(44004, "文本消息内容为空"),
    AUDIO_CONTENT_REVIEW_FAILED(44008, "音频内容审核失败"),
    NEWS_AUDIO_REVIEW_FAILED(44009, "图文中的音频内容审核失败"),
    MEDIA_SIZE_EXCEEDED(45001, "多媒体文件大小超过限制"),
    MESSAGE_CONTENT_EXCEEDED(45002, "消息内容超过限制"),
    TITLE_EXCEEDED(45003, "标题字段超过限制"),
    DESCRIPTION_EXCEEDED(45004, "描述字段超过限制"),
    LINK_EXCEEDED(45005, "链接字段超过限制"),
    IMAGE_LINK_EXCEEDED(45006, "图片链接字段超过限制"),
    VOICE_DURATION_EXCEEDED(45007, "语音播放时间超过限制"),
    NEWS_EXCEEDED(45008, "图文消息超过限制"),
    API_CALL_EXCEEDED(45009, "接口调用超过限制"),
    MENU_COUNT_EXCEEDED(45010, "创建菜单个数超过限制"),
    API_CALL_FREQUENT(45011, "API 调用太频繁，请稍候再试"),
    REPLY_TIME_EXCEEDED(45015, "回复时间超过限制"),
    SYSTEM_GROUP_MODIFICATION(45016, "系统分组，不允许修改"),
    GROUP_NAME_TOO_LONG(45017, "分组名字过长"),
    GROUP_COUNT_EXCEEDED(45018, "分组数量超过上限"),
    CUSTOMER_SERVICE_MESSAGE_EXCEEDED(45047, "客服接口下行条数超过上限"),
    MENU_CONTAINS_UNLINKED_MINIAPP(45064, "创建菜单包含未关联的小程序"),
    DUPLICATE_CLIENTMSGID(45065, "相同 clientmsgid 已存在群发记录，返回数据中带有已存在的群发任务的 msgid"),
    RAPID_CLIENTMSGID_RETRY(45066, "相同 clientmsgid 重试速度过快，请间隔1分钟重试"),
    CLIENTMSGID_LENGTH_EXCEEDED(45067, "clientmsgid 长度超过限制"),
    AUTHOR_LENGTH_EXCEEDED(45110, "作者字数超出限制"),
    NO_MEDIA_DATA(46001, "不存在媒体数据"),
    NO_MENU_VERSION(46002, "不存在的菜单版本"),
    NO_MENU_DATA(46003, "不存在的菜单数据"),
    NO_USER(46004, "不存在的用户"),
    JSON_XML_PARSING_ERROR(47001, "解析 JSON/XML 内容错误"),
    INVALID_PARAMETER_VALUE(47003, "参数值不符合限制要求，详情可参考参数值内容限制说明"),
    API_NOT_AUTHORIZED(48001, "api 功能未授权，请确认公众号已获得该接口，可以在公众平台官网 - 开发者中心页中查看接口权限"),
    USER_BLOCKS_MESSAGES(48002, "粉丝拒收消息（粉丝在公众号选项中，关闭了 “ 接收消息 ” ）"),
    API_BLOCKED(48004, "api 接口被封禁，请登录 mp.weixin.qq.com 查看详情"),
    API_MATERIAL_PROTECTED(48005, "api 禁止删除被自动回复和自定义菜单引用的素材"),
    API_CLEAR_LIMIT_EXCEEDED(48006, "api 禁止清零调用次数，因为清零次数达到上限"),
    NO_MESSAGE_TYPE_PERMISSION(48008, "没有该类型消息的发送权限"),
    DRAFT_PREVIEW_RESTRICTED(48021, "自动保存的草稿无法预览/发送，请先手动保存草稿"),
    API_NOT_AUTHORIZED_FOR_USER(50001, "用户未授权该 api"),
    USER_RESTRICTED(50002, "用户受限，可能是违规后接口被封禁"),
    USER_NOT_SUBSCRIBED(50005, "用户未关注公众号"),
    PUBLISH_BANNED(53500, "发布功能被封禁"),
    FREQUENT_PUBLISH_REQUEST(53501, "频繁请求发布"),
    INVALID_PUBLISH_ID(53502, "Publish ID 无效"),
    INVALID_ARTICLE_ID(53600, "Article ID 无效"),
    INVALID_PARAMETER(61451, "参数错误 (invalid parameter)"),
    INVALID_KF_ACCOUNT(61452, "无效客服账号 (invalid kf_account)"),
    KF_ACCOUNT_EXISTS(61453, "客服账号已存在 (kf_account exsited)"),
    INVALID_KF_ACCOUNT_LENGTH(61454, "客服账号名长度超过限制 ( 仅允许 10 个英文字符，不包括 @ 及 @ 后的公众号的微信号 )(invalid kf_acount length)"),
    ILLEGAL_KF_ACCOUNT_CHARACTERS(61455, "客服账号名包含非法字符 ( 仅允许英文 + 数字 )(illegal character in kf_account)"),
    KF_ACCOUNT_COUNT_EXCEEDED(61456, "客服账号个数超过限制 (10 个客服账号 )(kf_account count exceeded)"),
    INVALID_AVATAR_TYPE(61457, "无效头像文件类型 (invalid file type)"),
    SYSTEM_ERROR(61450, "系统错误 (system error)"),
    INVALID_DATE_FORMAT(61500, "日期格式错误"),
    MISSING_PARAMETERS(63001, "部分参数为空"),
    INVALID_SIGNATURE(63002, "无效的签名"),
    NO_PERSONALIZED_MENU(65301, "不存在此 menuid 对应的个性化菜单"),
    NO_CORRESPONDING_USER(65302, "没有相应的用户"),
    NO_DEFAULT_MENU(65303, "没有默认菜单，不能创建个性化菜单"),
    EMPTY_MATCHRULE(65304, "MatchRule 信息为空"),
    PERSONALIZED_MENU_LIMIT(65305, "个性化菜单数量受限"),
    NO_PERSONALIZED_MENU_SUPPORT(65306, "不支持个性化菜单的账号"),
    EMPTY_PERSONALIZED_MENU(65307, "个性化菜单信息为空"),
    NO_RESPONSE_TYPE_BUTTON(65308, "包含没有响应类型的 button"),
    PERSONALIZED_MENU_OFF(65309, "个性化菜单开关处于关闭状态"),
    MISSING_COUNTRY_INFO(65310, "填写了省份或城市信息，国家信息不能为空"),
    MISSING_PROVINCE_INFO(65311, "填写了城市信息，省份信息不能为空"),
    ILLEGAL_COUNTRY_INFO(65312, "不合法的国家信息"),
    ILLEGAL_PROVINCE_INFO(65313, "不合法的省份信息"),
    ILLEGAL_CITY_INFO(65314, "不合法的城市信息"),
    EXCESSIVE_DOMAIN_JUMPS(65316, "该公众号的菜单设置了过多的域名外跳（最多跳转到 3 个域名的链接）"),
    ILLEGAL_URL(65317, "不合法的 URL"),
    INVALID_SIGNATURE_2(87009, "无效的签名"),
    INVALID_POST_DATA(9001001, "POST 数据参数不合法"),
    REMOTE_SERVICE_UNAVAILABLE(9001002, "远端服务不可用"),
    INVALID_TICKET(9001003, "Ticket 不合法"),
    SHAKE_USERINFO_FAILED(9001004, "获取摇周边用户信息失败"),
    MERCHANT_INFO_FAILED(9001005, "获取商户信息失败"),
    OPENID_FAILED(9001006, "获取 OpenID 失败"),
    MISSING_UPLOAD_FILE(9001007, "上传文件缺失"),
    INVALID_UPLOAD_FILE_TYPE(9001008, "上传素材的文件类型不合法"),
    INVALID_UPLOAD_FILE_SIZE(9001009, "上传素材的文件尺寸不合法"),
    UPLOAD_FAILED(9001010, "上传失败"),
    ILLEGAL_ACCOUNT(9001020, "账号不合法"),
    LOW_DEVICE_ACTIVATION_RATE(9001021, "已有设备激活率低于 50% ，不能新增设备"),
    INVALID_DEVICE_APPLICATION_COUNT(9001022, "设备申请数不合法，必须为大于 0 的数字"),
    PENDING_DEVICE_ID_APPLICATION(9001023, "已存在审核中的设备 ID 申请"),
    EXCESSIVE_DEVICE_ID_QUERY(9001024, "一次查询设备 ID 数量不能超过 50"),
    ILLEGAL_DEVICE_ID(9001025, "设备 ID 不合法"),
    ILLEGAL_PAGE_ID(9001026, "页面 ID 不合法"),
    ILLEGAL_PAGE_PARAMETERS(9001027, "页面参数不合法"),
    EXCESSIVE_PAGE_ID_DELETION(9001028, "一次删除页面 ID 数量不能超过 10"),
    PAGE_APPLIED_TO_DEVICE(9001029, "页面已应用在设备中，请先解除应用关系再删除"),
    EXCESSIVE_PAGE_ID_QUERY(9001030, "一次查询页面 ID 数量不能超过 50"),
    ILLEGAL_TIME_RANGE(9001031, "时间区间不合法"),
    INVALID_DEVICE_PAGE_BINDING(9001032, "保存设备与页面的绑定关系参数错误"),
    ILLEGAL_STORE_ID(9001033, "门店 ID 不合法"),
    EXCESSIVE_DEVICE_REMARK(9001034, "设备备注信息过长"),
    ILLEGAL_DEVICE_APPLICATION_PARAMETERS(9001035, "设备申请参数不合法"),
    ILLEGAL_QUERY_BEGIN(9001036, "查询起始值 begin 不合法");

    private final Integer code;
    private final String desc;

    WxRespEnum(Integer code, String desc) {
        this.code = code;
        this.desc = desc;
    }

    public Integer getCode() {
        return code;
    }

    public String getDesc() {
        return desc;
    }

    public static WxRespEnum fromCode(Integer code) {
        for (WxRespEnum responseCode : values()) {
            if (responseCode.getCode().equals(code)) {
                return responseCode;
            }
        }
        return null;
    }
}